#index:
#    path: /
#    controller: App\Controller\DefaultController::index

check_login:
  path: /check/login
  controller: App\Controller\UserController::checkLogin

login:
  path: /login
  controller: App\Controller\UserController::login

logout:
  path: /logout
  controller: App\Controller\UserController::logout

add_cookie:
  path: /add/cookie
  controller: App\Controller\UserController::addCookie

clear_cookie:
  path: /clear/cookie
  controller: App\Controller\UserController::clearCookie
